import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "./SideMenu";
import { ThemeProvider } from "@/components/theme-provider";
import ConsoleWindow from "@/components/console-window/console-window";
import { ConsoleWindowProvider } from "@/components/console-window/console-window-provider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          inter.className,
          "overflow-hidden relative w-screen h-screen"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConsoleWindowProvider>
            <div className="flex flex-row h-screen">
              <SideMenu />
              <main className="flex-1 px-4 overflow-scroll pb-16">
                {children}
              </main>
            </div>
            {modal}
            <ConsoleWindow />
          </ConsoleWindowProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
